### ISSUE TITLE
Bad ls colors in Data partition

### ISSUE THREAD

**Issue by rafli-sss** [dracula/dircolors#1] opened 2022-08-20 14:54 UTC
![Screenshot from 2022-08-20 21-20-39](https://user-images.githubusercontent.com/92916692/185751956-3406b4b4-7429-47ca-9d0c-d0812b70d95f.png)
I have used : 
- [Alacritty](https://github.com/dracula/alacritty)
- [Xresources](https://github.com/dracula/xresources)
- [dircolors](https://github.com/dracula/dircolors)

When i change to nord colorscheme dircolors : 
![Screenshot from 2022-08-20 21-26-22](https://user-images.githubusercontent.com/92916692/185752278-d180314c-4d3c-4f89-94c2-930c6a9dcd29.png)

What's wrong?
What is the correct way to apply?

**Comment by scop** [comment] 2022-08-20 20:11
I don't know what "data partition" means, but I'm guessing it's a Windows partition. Is it a FAT formatted one? IIRC at least some such filesystems used to result in all files being executable when mounted, maybe that's what you're seeing there.

I'm also unsure if I can answer the "what's wrong" question. I'd rather be told what you think is wrong, and could then comment what I think could be done with it. Anyway, if my guess is correct, then there's nothing wrong really, the colors work as intended -- the files are executable and are colored as such. If you don't want the files to be executable, the umask/dmask/fmask/showexec mount options for your partition might be something to look into.

Closing, let me know if I misunderstood something or guessed wrong.

**Closed as completed by scop** 2022-08-20 20:11 UTC
